name: Build and deploy mkdocs website

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  semver:
    name: Caluclate Version
    runs-on: ubuntu-latest
    outputs:
      semver: ${{ steps.semver.outputs.version_tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: semver
        uses: paulhatch/semantic-version@v5.3.0
        with:
          tag_prefix: "v"
          version_format: "${major}.${minor}.${patch}"

  build-mkdocs:
    name: Build mkdocs site
    needs: semver
    runs-on: ubuntu-latest
    outputs:
      built: ${{ steps.changes.outputs.project }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check for changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            project:
              - 'mkdocs/**'

      - name: Install python 3.x
        uses: actions/setup-python@v5
        if: steps.changes.outputs.project == 'true'
        with:
          python-version: 3.x

      - name: setup caching
        uses: actions/cache@v4
        if: steps.changes.outputs.project == 'true'
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Install pyhton modules
        run: pip install -r requirements.txt
        if: steps.changes.outputs.project == 'true'
        working-directory: ./mkdocs

      - name: MkDocs build
        run: mkdocs build
        if: steps.changes.outputs.project == 'true'
        working-directory: ./mkdocs

      - name: Upload site
        uses: actions/upload-artifact@v4
        if: steps.changes.outputs.project == 'true'
        with:
          name: mkdocs
          path: "mkdocs/site/*"
          if-no-files-found: error
          retention-days: 1

  build-hugo:
    name: Build hugo site
    needs: semver
    runs-on: ubuntu-latest
    outputs:
      built: ${{ steps.changes.outputs.project }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check for changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            project:
              - 'hugo/**'

      - name: Setup caching
        if: steps.changes.outputs.project == 'true'
        uses: actions/cache@v4
        with:
          path: /home/runner/.cache/hugo_cache
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-

      - name: Setup Hugo
        if: steps.changes.outputs.project == 'true'
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "latest"

      - name: Build
        if: steps.changes.outputs.project == 'true'
        run: hugo --minify
        working-directory: ./hugo

      - name: Upload site
        uses: actions/upload-artifact@v4
        if: steps.changes.outputs.project == 'true'
        with:
          name: hugo
          path: "hugo/public/*"
          if-no-files-found: error
          retention-days: 1

  deploy:
    name: Deploy adreasnow.com
    runs-on: ubuntu-latest
    needs:
      - semver
      - build-mkdocs
      - build-hugo
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      # HUGO

      - name: Backup academic if hugo, but not mkdocs
        if: ${{ (needs.build-hugo.outputs.built == 'true') && (needs.build-mkdocs.outputs.built == 'false') }}
        uses: actions/upload-artifact@v4
        with:
          name: academic
          path: "academic/*"
          if-no-files-found: error
          retention-days: 1

      - name: Delete everything
        if: needs.build-hugo.outputs.built == 'true'
        run: rm -rf *

      - name: Put hugo in place
        if: needs.build-hugo.outputs.built == 'true'
        uses: actions/download-artifact@v4
        with:
          name: hugo
          path: ./

      - name: Restore academic if hugo, but not mkdocs
        if: ${{ (needs.build-hugo.outputs.built == 'true') && (needs.build-mkdocs.outputs.built == 'false') }}
        uses: actions/download-artifact@v4
        with:
          name: academic
          path: academic

      - name: Restore CNAME
        if: needs.build-hugo.outputs.built == 'true'
        run: echo 'adreasnow.com' > CNAME

      # MKDOCS

      - name: Delete old mkdocs
        if: needs.build-mkdocs.outputs.built == 'true'
        run: rm -rf academic

      - name: Put new mkdocs in place
        if: needs.build-mkdocs.outputs.built == 'true'
        uses: actions/download-artifact@v4
        with:
          name: mkdocs
          path: academic

      - name: Push the new site
        if: ${{ (needs.build-hugo.outputs.built == 'true') || (needs.build-mkdocs.outputs.built == 'true') }}
        run: |
          git config user.name "Adrea Snow"
          git config user.email adrea.snow@gmail.com
          git add .
          git commit -m ${{ needs.semver.outputs.semver }}
          git push

  tag:
    name: Tag the main branch
    runs-on: ubuntu-latest
    if: ${{ (needs.build-hugo.outputs.built == 'true') || (needs.build-mkdocs.outputs.built == 'true') }}
    needs:
      - semver
      - build-mkdocs
      - build-hugo
      - deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Tag the commit
        uses: actions/github-script@v7
        with:
          retries: 3
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ needs.semver.outputs.semver }}',
              sha: context.sha
            })
