name: Build and deploy adreasnow.com

on:
  push:
    branches:
     - main
     
permissions:
  id-token: write
  contents: write
  checks: write

jobs:
  deploy:
    name: Deploy adreasnow.com
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name adreasnow
          git config user.email adrea.snow@gmail.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x # (3)!
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-minify-plugin \
              lightgallery \
              mkdocs-material-extensions \
              mkdocs \
              mkdocs-material
      - run: mkdocs gh-deploy --force