name: Build and deploy mkdocs website

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  semver:
    name: Caluclate Version
    runs-on: ubuntu-latest
    outputs:
      semver: ${{ steps.semver.outputs.version_tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: semver
        uses: paulhatch/semantic-version@v5.3.0
        with:
          tag_prefix: "v"
          version_format: "${major}.${minor}.${patch}"
      - uses: actions/github-script@v7
        with:
          retries: 3
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ steps.semver.outputs.version_tag }}',
              sha: context.sha
            })

  build-mkdocs:
    name: Build mkdocs site
    needs: semver
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure Git Credentials
        run: |
          git config user.name "Adrea Snow"
          git config user.email adrea.snow@gmail.com

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - run: pip install -r requirements.txt
        working-directory: ./mkdocs

      - run: mkdocs build
        working-directory: ./mkdocs

      - uses: actions/upload-artifact@v4
        with:
          name: mkdocs
          path: "mkdocs/site/*"
          if-no-files-found: error
          retention-days: 1

  build-hugo:
    name: Build hugo site
    needs: semver
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

  deploy:
    name: Deploy adreasnow.com
    runs-on: ubuntu-latest
    needs:
      - semver
      - build-mkdocs
      - build-hugo
    steps:
      - uses: actions/checkout@v4
        with:
          ref: gh-pages

      - run: rm -rf *

      - run: |
          echo '<meta http-equiv="refresh" content="0; url=https://adreasnow.com/academic/" />' > index.html
          echo 'adreasnow.com' > CNAME

      - uses: actions/download-artifact@v4
        with:
          name: mkdocs
          path: academic

      # - uses: actions/download-artifact@v4
      #   with:
      #     name: hugo
      #     path: ./

      - name: Configure Git Credentials
        run: |
          git config user.name "Adrea Snow"
          git config user.email adrea.snow@gmail.com
          git add .
          git commit -m ${{ needs.semver.outputs.semver }}
          git push --force
